---
title: "Eduvos Graduate Analysis Report"
author: "Onthatile Lebogo"
format: pdf
editor: visual
---

## Introduction

The purpose of this analysis is to give the institution's stakeholders insight on which IT courses to offer and the content needed in those respective courses based off the needs and trends in the IT industry. The IT industry is vast so to achieve this we look at multiple variables such as the top programming languages, databases, web frameworks, cloud platforms, industries, AI developer tools, AI search tools and the employment rate of these IT courses.

##Data Overview The dataset consists of 86 columns and 31821 rows. I selected the relevant columns for the task at hand. The columns were Campus, StudyField, Branch, Role, EduLevel, ProgLang, Databases, Platform, WebFramework, Industry, AISearch, AITool, Employment. The dataset contained missing values so I removed rows that contained "NA". I changed the "Umhlanga Campus" to "Durban Campus" because in the institution it is considered the as the same campus. I filtered the the dataset to only show the top 5 campuses with the most responseses.

## Insights and Analysis

### Programming Languages

The top programming languages are the following: Javascript, HTML/CSS, Python, TypeScript, Bash/Shell, Java, C#, etc. The trend with these programming languages is where most IT gradutes find themselves in, web development. In these times, web developers are needed to build and maintain websites for small businesses to large businesses. Some of the programming languages like Python and TypeScript have grown in popularity due to their ease of use.

### Databases

The common databases are SQL databases. There are new databases that are commonly due to there ability to collect real-time data and process the data in real time.

### Web Frameworks

The popular Web Frameworks promote ease of use, understandability, cross-platform capabilities and high performance reactive websites such as React and Angular. Node.js is a popular server used in the web development community.

### Cloud Platforms

The popular cloud platforms are the ones with the most secure servers and hosting space providing clients with a vast option for scalability for their business or personal needs.

### AI developer Tools

AI Developer Tools has helped industries produce remarkable results in regards to efficiency, accuracy and decision making.

## Recommendations

### Curriculum Development

All IT students that are studying a web development module should React and Nod.js to their content.

### Focus Areas

All IT fields should learn the basics of a popular cloud platform such as AWS and Microsoft Azure.

###Indusrty Alignment All IT field should be given elective module the go through the basics of certain industries that their likely to be employed in.

##Conclusion When it comes to tech tools there are at least 5 tools that are popular and commonly used in the work place. This makes it easy to decide on the content of the modules. However these tech tools are fairly new and IT is a forever changing field so this sort of analysis needs to be done yearly to ensure the students get up to date education.

##GitHub Repository https://github.com/nthatilebogo/R-Studio-Shiny-Eduvos-Graduate

## Bibliography

Wickham, H. (2016) ggplot2: Elegant Graphics for Data Analysis. 2nd edn. New York: Springer-Verlag. Available at: https://ggplot2.tidyverse.org (Accessed: 14 March 2025).

Chang, W. (2021) R Graphics Cookbook. 2nd edn. Sebastopol: O'Reilly Media. Available at: https://r-graphics.org (Accessed: 14 March 2025).

Xie, Y. (2022) R Markdown: The Definitive Guide. 2nd edn. Boca Raton: CRC Press. Available at: https://bookdown.org/yihui/rmarkdown (Accessed: 14 March 2025).

Cheng, J., Karambelkar, B. and Xie, Y. (2021) Leaflet: Create Interactive Web Maps with the JavaScript 'Leaflet' Library. R package version 2.0.4.1. Available at: https://cran.r-project.org/web/packages/leaflet/index.html (Accessed: 14 March 2025).

Sievert, C. (2020) Interactive Web-Based Data Visualization with R, plotly, and shiny. Boca Raton: CRC Press. Available at: https://plotly-r.com (Accessed: 14 March 2025).

Navarro, D.J. (2021) Learning Statistics with R: A Tutorial for Psychology Students and Other Beginners. Version 0.6.1. Adelaide: University of Adelaide. Available at: https://learningstatisticswithr.com (Accessed: 14 March 2025).

RStudio, PBC (2022) Shiny: Web Application Framework for R. R package version 1.7.1. Available at: https://shiny.rstudio.com (Accessed: 14 March 2025).

RStudio, PBC (2022) Quarto: Open-Source Scientific and Technical Publishing System. Available at: https://quarto.org (Accessed: 14 March 2025).

Posit Community (2023) 'RShiny: Update ggplot2 geom_col() graph using updateSelectizeInput()', Posit Community Forum. Available at: https://forum.posit.co/t/rshiny-update-ggplot2-geom-col-graph-using-updateselectizeinput/171044 (Accessed: 14 March 2025).

Silva, F.C.M. (2018) 'Making a bar graph with ggplot and Shiny in R', Stack Overflow. Available at: https://stackoverflow.com/questions/53156749/making-a-bar-graph-with-ggplot-and-shiny-in-r (Accessed: 14 March 2025).

Duke University Libraries (2024) 'Visualization with ggplot2 - R/Tidyverse/Quarto - get started', Introduction to R. Available at: https://intro2r.library.duke.edu/viz.html (Accessed: 14 March 2025).

Posit Community (2022) 'Clustered Bar chart in R shiny', Posit Community Forum. Available at: https://forum.posit.co/t/clustered-bar-chart-in-r-shiny/147814 (Accessed: 14 March 2025).

Harvard University (2025) 'Chapter 8 ggplot2', Introduction to Data Science. Available at: https://rafalab.dfci.harvard.edu/dsbook/ggplot2.html (Accessed: 14 March 2025).

Quarto (2025) 'Dashboards with Shiny for R', Quarto Documentation. Available at: https://quarto.org/docs/dashboards/interactivity/shiny-r.html (Accessed: 14 March 2025).

Reddit User (2023) 'Quarto document rendered via quarto::quarto_render()', Reddit. Available at: https://www.reddit.com/r/RStudio/comments/14pa2uf/quarto_document_rendered_via_quartoquarto_render (Accessed: 14 March 2025).

Posit Community (2022) 'R Shiny Basic App: Bar plot using ggplot', YouTube. Available at: https://www.youtube.com/watch?v=LnmMPm1lTAg (Accessed: 14 March 2025).

Posit Community (2022) 'R Shiny Basic App: Interactive ggplot Bar Chart using Shiny', YouTube. Available at: https://www.youtube.com/watch?v=rlcUiSw49FY (Accessed: 14 March 2025).

Harvard University (2025) 'Graphs, tables, and maps', Telling Stories with Data. Available at: https://tellingstorieswithdata.com/05-graphs_tables_maps.html (Accessed: 14 March 2025).

RStudio, PBC (2022) ggplot2: Create Elegant Data Visualisations Using the Grammar of Graphics. R package version 3.3.5. Available at: https://cran.r-project.org/web/packages/ggplot2/index.html (Accessed: 14 March 2025).

RStudio, PBC (2022) Shiny Dashboard: Create Dashboards with 'Shiny'. R package version 0.7.2. Available at: https://cran.r-project.org/web/packages/shinydashboard/index.html (Accessed: 14 March 2025).
